export interface LocalizedString {
  zh: string;
  en: string;
}

export interface Category {
  id: number;
  name: LocalizedString;
  image: string;
  slug: string;
}

export interface Product {
  id: string;
  title: LocalizedString;
  price: number;
  originalPrice: number;
  image: string;
  tags: string[];
  tags_zh?: string[];
  marketInsight?: LocalizedString;
  categorySlug: string;
}

export const categories: Category[] = [
  {
    id: 1,
    name: { zh: "主食罐头", en: "Wet Food" },
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=800&q=80",
    slug: "canned-food",
  },
  {
    id: 2,
    name: { zh: "零食猫条", en: "Cat Treats" },
    image: "https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=800&q=80",
    slug: "cat-strips",
  },
  {
    id: 3,
    name: { zh: "全价猫粮", en: "Dry Food" },
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    slug: "dry-food",
  },
  {
    id: 4,
    name: { zh: "猫砂用品", en: "Litter & Hygiene" },
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80",
    slug: "litter",
  },
  {
    id: 5,
    name: { zh: "烘焙猫粮", en: "Baked Kibble" },
    image: "https://images.unsplash.com/photo-1623366302587-b38b1ddaefd9?auto=format&fit=crop&w=800&q=80",
    slug: "baked-food",
  },
  {
    id: 6,
    name: { zh: "冻干猫粮", en: "Freeze-Dried" },
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    slug: "freeze-dried-food",
  },
];

export const products: Product[] = [
  // --- 主食罐头 (Canned Food) ---
  {
    id: "1850020044731420674",
    title: { zh: "慕斯牛肉罐头 85g", en: "Beef Mousse Canned Food 85g" },
    price: 1.99,
    originalPrice: 2.99,
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=800&q=80",
    tags: ["Best Seller", "Sale"],
    tags_zh: ["爆款", "特价"],
    marketInsight: { zh: "复购率 > 40%。精品店高利润单品。", en: "Reorder rate > 40%. High margin item for boutique stores." },
    categorySlug: "canned-food",
  },
  {
    id: "1850020258724810754",
    title: { zh: "慕斯鱼肉罐头 85g", en: "Fish Mousse Canned Food 85g" },
    price: 1.99,
    originalPrice: 2.99,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Hot"],
    tags_zh: ["热销"],
    marketInsight: { zh: "猫咪嗜口性极佳。", en: "High palatability for cats." },
    categorySlug: "canned-food",
  },
  {
    id: "can-3",
    title: { zh: "鸡肉丝主食罐 170g", en: "Shredded Chicken Wet Food 170g" },
    price: 2.50,
    originalPrice: 3.50,
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=800&q=80",
    tags: ["Large Can"],
    tags_zh: ["大罐装"],
    marketInsight: { zh: "多猫家庭首选。", en: "Preferred for multi-cat households." },
    categorySlug: "canned-food",
  },
  {
    id: "can-4",
    title: { zh: "金枪鱼虾仁罐头 85g", en: "Tuna & Shrimp Feast 85g" },
    price: 2.10,
    originalPrice: 2.80,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Seafood"],
    tags_zh: ["海鲜口味"],
    marketInsight: { zh: "富含Omega-3。", en: "Rich in Omega-3." },
    categorySlug: "canned-food",
  },
  {
    id: "can-5",
    title: { zh: "幼猫离乳主食罐 85g", en: "Kitten Weaning Mousse 85g" },
    price: 2.20,
    originalPrice: 3.00,
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=800&q=80",
    tags: ["Kitten", "Easy Digest"],
    tags_zh: ["幼猫", "易消化"],
    marketInsight: { zh: "幼猫断奶期必备。", en: "Essential for kitten weaning." },
    categorySlug: "canned-food",
  },
  {
    id: "can-6",
    title: { zh: "老年猫呵护罐头 85g", en: "Senior Cat Care Formula 85g" },
    price: 2.15,
    originalPrice: 2.90,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Low Phosphorus"],
    tags_zh: ["低磷"],
    marketInsight: { zh: "低磷配方保护肾脏。", en: "Low phosphorus for kidney health." },
    categorySlug: "canned-food",
  },

  // --- 零食猫条 (Cat Strips) ---
  {
    id: "1946154753693286401",
    title: { zh: "鸽肉羊奶主食猫条 15g*5", en: "Pigeon & Goat Milk Creamy Treat 15g*5" },
    price: 1.50,
    originalPrice: 2.50,
    image: "https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=800&q=80",
    tags: ["New", "BOGO 50%"],
    tags_zh: ["新品", "第二件半价"],
    marketInsight: { zh: "独特口味，高复购。", en: "Unique flavor, high repurchase." },
    categorySlug: "cat-strips",
  },
  {
    id: "strip-2",
    title: { zh: "金枪鱼猫条 15g*20", en: "Tuna Creamy Treats Value Pack 15g*20" },
    price: 4.50,
    originalPrice: 6.50,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Value Pack"],
    tags_zh: ["量贩装"],
    marketInsight: { zh: "家庭装更实惠。", en: "Value pack for savings." },
    categorySlug: "cat-strips",
  },
  {
    id: "strip-3",
    title: { zh: "三文鱼鱼子酱猫条 15g*5", en: "Salmon & Caviar Luxury Treat 15g*5" },
    price: 2.00,
    originalPrice: 3.00,
    image: "https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=800&q=80",
    tags: ["Luxury"],
    tags_zh: ["奢华"],
    marketInsight: { zh: "高端零食体验。", en: "Premium treat experience." },
    categorySlug: "cat-strips",
  },
  {
    id: "strip-4",
    title: { zh: "混合口味猫条桶 100支", en: "Mixed Flavor Party Bucket 100 Sticks" },
    price: 15.00,
    originalPrice: 20.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Super Value"],
    tags_zh: ["超值"],
    marketInsight: { zh: "派对桶装，销量王。", en: "Party bucket, top seller." },
    categorySlug: "cat-strips",
  },
  {
    id: "strip-5",
    title: { zh: "鸡肉蔓越莓猫条 15g*5", en: "Chicken & Cranberry Urinary Care 15g*5" },
    price: 1.40,
    originalPrice: 2.00,
    image: "https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=800&q=80",
    tags: ["Urinary Care"],
    tags_zh: ["泌尿呵护"],
    marketInsight: { zh: "呵护泌尿系统健康。", en: "Supports urinary health." },
    categorySlug: "cat-strips",
  },

  // --- 全价猫粮 (Dry Food) ---
  {
    id: "mock-1",
    title: { zh: "全价鲜肉猫粮 1.5kg", en: "Fresh Meat Dry Food 1.5kg" },
    price: 12.00,
    originalPrice: 18.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Premium"],
    tags_zh: ["高端"],
    marketInsight: { zh: "鲜肉含量高。", en: "High fresh meat content." },
    categorySlug: "dry-food",
  },
  {
    id: "mock-catfood-1",
    title: { zh: "无谷鸡肉全价猫粮 5kg", en: "Grain-Free Chicken Dry Food 5kg" },
    price: 38.00,
    originalPrice: 48.00,
    image: "https://images.unsplash.com/photo-1623366302587-b38b1ddaefd9?auto=format&fit=crop&w=800&q=80",
    tags: ["Imported"],
    tags_zh: ["进口"],
    marketInsight: { zh: "无谷配方低敏。", en: "Grain-free hypoallergenic." },
    categorySlug: "dry-food",
  },
  {
    id: "mock-catfood-3",
    title: { zh: "三文鱼成猫粮 10kg", en: "Salmon Adult Cat Food 10kg" },
    price: 70.00,
    originalPrice: 85.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Bulk Size"],
    tags_zh: ["大包装"],
    marketInsight: { zh: "繁育舍专供。", en: "Breeder exclusive." },
    categorySlug: "dry-food",
  },
  {
    id: "dry-4",
    title: { zh: "室内成猫粮 2kg", en: "Indoor Cat Formula 2kg" },
    price: 16.00,
    originalPrice: 22.00,
    image: "https://images.unsplash.com/photo-1623366302587-b38b1ddaefd9?auto=format&fit=crop&w=800&q=80",
    tags: ["Odor Control"],
    tags_zh: ["除臭"],
    marketInsight: { zh: "减少便臭。", en: "Reduces litter odor." },
    categorySlug: "dry-food",
  },
  {
    id: "dry-5",
    title: { zh: "去毛球猫粮 2kg", en: "Hairball Control Formula 2kg" },
    price: 18.00,
    originalPrice: 24.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Hairball"],
    tags_zh: ["化毛"],
    marketInsight: { zh: "有效排出毛球。", en: "Effective hairball elimination." },
    categorySlug: "dry-food",
  },

  // --- 猫砂用品 (Litter) ---
  {
    id: "mock-litter-1",
    title: { zh: "混合猫砂 2.5kg", en: "Mixed Cat Litter 2.5kg" },
    price: 3.50,
    originalPrice: 5.00,
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80",
    tags: ["Odor Control"],
    tags_zh: ["强力除臭"],
    marketInsight: { zh: "结团快，不粘底。", en: "Fast clumping, non-stick." },
    categorySlug: "litter",
  },
  {
    id: "mock-litter-2",
    title: { zh: "豆腐猫砂 6L", en: "Tofu Cat Litter 6L" },
    price: 24.90,
    originalPrice: 35.00,
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80",
    tags: ["Flushable"],
    tags_zh: ["可冲马桶"],
    marketInsight: { zh: "环保可降解。", en: "Eco-friendly and biodegradable." },
    categorySlug: "litter",
  },
  {
    id: "litter-3",
    title: { zh: "膨润土猫砂 10kg", en: "Bentonite Cat Litter 10kg" },
    price: 45.00,
    originalPrice: 55.00,
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80",
    tags: ["Strong Clumping"],
    tags_zh: ["强力结团"],
    marketInsight: { zh: "性价比之选。", en: "Cost-effective choice." },
    categorySlug: "litter",
  },
  {
    id: "litter-4",
    title: { zh: "绿茶味豆腐砂 6L", en: "Green Tea Tofu Litter 6L" },
    price: 25.90,
    originalPrice: 35.00,
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80",
    tags: ["Fresh Scent"],
    tags_zh: ["清新"],
    marketInsight: { zh: "自然清香掩盖异味。", en: "Natural scent masks odors." },
    categorySlug: "litter",
  },
  {
    id: "litter-5",
    title: { zh: "除臭珠 250g", en: "Deodorant Beads 250g" },
    price: 9.90,
    originalPrice: 19.90,
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80",
    tags: ["Booster"],
    tags_zh: ["伴侣"],
    marketInsight: { zh: "搭配猫砂使用。", en: "Use with any litter." },
    categorySlug: "litter",
  },

  // --- 烘焙猫粮 (Baked Food) ---
  {
    id: "mock-catfood-2",
    title: { zh: "低温烘焙鸭肉猫粮 2kg", en: "Low-Temp Baked Duck Cat Food 2kg" },
    price: 158.00,
    originalPrice: 188.00,
    image: "https://images.unsplash.com/photo-1623366302587-b38b1ddaefd9?auto=format&fit=crop&w=800&q=80",
    tags: ["New Arrival"],
    tags_zh: ["新品"],
    marketInsight: { zh: "保留更多营养。", en: "Retains more nutrients." },
    categorySlug: "baked-food",
  },
  {
    id: "baked-2",
    title: { zh: "低温烘焙鸡肉猫粮 1.5kg", en: "Low-Temp Baked Chicken Cat Food 1.5kg" },
    price: 138.00,
    originalPrice: 168.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Non-Greasy"],
    tags_zh: ["0油感"],
    marketInsight: { zh: "减少黑下巴。", en: "Reduces feline chin acne." },
    categorySlug: "baked-food",
  },
  {
    id: "baked-3",
    title: { zh: "烘焙粮试吃装 50g*3", en: "Baked Food Sample Pack 50g*3" },
    price: 9.90,
    originalPrice: 19.90,
    image: "https://images.unsplash.com/photo-1623366302587-b38b1ddaefd9?auto=format&fit=crop&w=800&q=80",
    tags: ["Trial"],
    tags_zh: ["尝鲜"],
    marketInsight: { zh: "低门槛尝试。", en: "Low barrier to try." },
    categorySlug: "baked-food",
  },
  {
    id: "baked-4",
    title: { zh: "全鱼烘焙猫粮 2kg", en: "Whole Fish Baked Cat Food 2kg" },
    price: 168.00,
    originalPrice: 198.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Coat Care"],
    tags_zh: ["美毛"],
    marketInsight: { zh: "亮毛护肤。", en: "Promotes shiny coat." },
    categorySlug: "baked-food",
  },

  // --- 冻干猫粮 (Freeze Dried Food) ---
  {
    id: "mock-freeze-1",
    title: { zh: "生骨肉冻干 500g", en: "Raw Bone & Meat Freeze-Dried 500g" },
    price: 128.00,
    originalPrice: 158.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Pure Meat"],
    tags_zh: ["纯肉"],
    marketInsight: { zh: "还原野性饮食。", en: "Restores ancestral diet." },
    categorySlug: "freeze-dried-food",
  },
  {
    id: "mock-3",
    title: { zh: "三文鱼冻干 50g", en: "Salmon Freeze-Dried 50g" },
    price: 39.90,
    originalPrice: 49.90,
    image: "https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=800&q=80",
    tags: ["BOGO"],
    tags_zh: ["买一送一"],
    marketInsight: { zh: "超高性价比。", en: "Great value." },
    categorySlug: "freeze-dried-food",
  },
  {
    id: "freeze-3",
    title: { zh: "鸡肉冻干粒 200g", en: "Chicken Freeze-Dried Cubes 200g" },
    price: 49.00,
    originalPrice: 69.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["High Protein"],
    tags_zh: ["高蛋白"],
    marketInsight: { zh: "增肌必备。", en: "Essential for muscle building." },
    categorySlug: "freeze-dried-food",
  },
  {
    id: "freeze-4",
    title: { zh: "鹌鹑蛋冻干 100g", en: "Quail Egg Freeze-Dried 100g" },
    price: 29.90,
    originalPrice: 39.90,
    image: "https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=800&q=80",
    tags: ["Yolk"],
    tags_zh: ["爆蛋"],
    marketInsight: { zh: "补充卵磷脂。", en: "Rich in lecithin." },
    categorySlug: "freeze-dried-food",
  },
  {
    id: "freeze-5",
    title: { zh: "多春鱼冻干 80g", en: "Capelin Freeze-Dried 80g" },
    price: 35.00,
    originalPrice: 45.00,
    image: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=800&q=80",
    tags: ["Whole Fish"],
    tags_zh: ["整鱼"],
    marketInsight: { zh: "猫咪爱不释手。", en: "Cats love it." },
    categorySlug: "freeze-dried-food",
  },
];
